version: '2'

services:
    web:
        container_name: web
        build:
            context: .
            dockerfile: opt/nginx/Dockerfile
        ports:
            - 80:80
            - 443:443
        depends_on:
            - php-fpm
            - app
        volumes_from:
            - app
        # volumes:
        #     - ./opt/nginx/nginx.conf:/etc/nginx/nginx.conf
        #     - ./opt/nginx/site.conf:/etc/nginx/conf.d/default.conf

    php-fpm:
        container_name: php-fpm
        build:
            context: .
            dockerfile: opt/php71/Dockerfile
        working_dir: /var/www
        depends_on:
            - redis
            - mariadb
            - app
        volumes_from:
          - app

    redis:
        container_name: redis
        image: redis

    rabbitmq:
        image: rabbitmq

    mariadb:
        container_name: mariadb
        image: mariadb:10.1
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=passmed
            - MYSQL_ROOT_PASSWORD=devpass
        # volumes:
            #- ./opt/db/db.sql:/docker-entrypoint-initdb.d/db.sql

    # appworker:
    #     container_name: appworker
    #     image: nginx:stable
    #     volumes_from:
    #         - app
    #     depends_on:
    #         - app
    #     entrypoint: /bin/sh -c /opt/app/entrypoint.sh
    #     volumes:
    #         - ./opt/app:/opt/app

    app:
        container_name: app
        image: busybox
        stdin_open: true
        volumes:
            - .:/var/www
